- name: Save Cookies File
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Download Video
        run: |
          yt-dlp --no-check-certificate \
            --cookies cookies.txt \
            -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" \
            --merge-output-format mp4 \
            -o "downloaded_video.mp4" \
            "${{ github.event.inputs.youtube_url }}"
